export const locales = ["es", "en"];

export const site = {
  name: "Bajío Logistics",
  tagline: "Tu carga en movimiento",
  location: "San Juan del Río, Querétaro, México",
  locationShort: "San Juan del Río, Querétaro",
  coverage: "Cobertura nacional",
  phone: null,
  email: null,
  whatsapp: "527711318149",
};

export const content = {
  es: {
    languageName: "Español",
    localeLabel: "ES",
    nav: [
      ["Inicio", "/es"],
      ["Nosotros", "/es/nosotros"],
      ["Servicios", "/es/servicios"],
      ["Cobertura", "/es/cobertura"],
      ["Clientes", "/es/clientes"],
      ["Proveedores", "/es/proveedores"],
      ["Contacto", "/es/contacto"],
    ],
    profile: { customer: "Cliente", carrier: "Proveedor", visitor: "Visitante" },
    headerCta: { customer: "Cotizar servicio", carrier: "Ser proveedor" },
    hero: {
      customer: {
        eyebrow: "SOLUCIONES LOGÍSTICAS CON COBERTURA NACIONAL",
        title: "Más que transporte,",
        accent: "soluciones que mueven tu negocio",
        body: "Coordinamos transporte, almacenamiento y logística integral para que tu cadena de suministro llegue más lejos.",
        primary: "Solicitar cotización",
        secondary: "Conocer nuestros servicios",
      },
      carrier: {
        eyebrow: "RED DE PROVEEDORES · OPERACIONES EN MÉXICO",
        title: "Crezcamos juntos",
        accent: "Forma parte de nuestra red",
        body: "Conecta tu capacidad operativa con oportunidades de transporte en diferentes regiones del país.",
        primary: "Quiero ser proveedor",
        secondary: "Ya soy proveedor",
      },
      visitor: {
        eyebrow: "BAJÍO LOGISTICS · TU CARGA EN MOVIMIENTO",
        title: "Logística que entiende",
        accent: "lo que tu operación necesita",
        body: "Conoce una forma más clara de mover mercancías, coordinar proveedores y tomar mejores decisiones.",
        primary: "Conocer Bajío Logistics",
        secondary: "Ver servicios",
      },
    },
    home: {
      introKicker: "Un aliado para tu operación",
      introTitle: "La logística también puede ser una ventaja competitiva",
      introBody: "En Bajío Logistics somos una empresa mexicana especializada en soluciones logísticas y transporte, con sede en San Juan del Río, Querétaro, y cobertura a nivel nacional.",
      introLink: "Conoce nuestra forma de trabajar",
      capabilitiesTitle: "¿Qué podemos hacer por tu empresa?",
      capabilitiesBody: "Acompañamos cada movimiento con coordinación, visibilidad y una red de proveedores confiables.",
      capabilities: [
        { icon: "truck", title: "Transporte de mercancías", body: "Unidades según las necesidades de cada operación." },
        { icon: "route", title: "Planeación logística", body: "Rutas eficientes y menor costo operativo." },
        { icon: "radar", title: "Gestión y seguimiento", body: "Control y visibilidad para tus envíos." },
        { icon: "gauge", title: "Optimización de costos", body: "Más eficiencia y rentabilidad para tu negocio." },
      ],
      servicesKicker: "Capacidades que conectan",
      servicesTitle: "Servicios para avanzar con dirección",
      servicesBody: "Desde un movimiento puntual hasta una operación que necesita orden, Bajío Logistics adapta la coordinación a tus prioridades.",
      servicesLink: "Ver todos los servicios",
      processKicker: "Cómo trabajamos",
      processTitle: "Una operación coordinada de principio a fin",
      process: [
        ["01", "Entendemos", "Conocemos tu operación, ruta y necesidades."],
        ["02", "Planeamos", "Definimos una solución clara para el movimiento."],
        ["03", "Coordinamos", "Alineamos proveedores, tiempos y comunicación."],
        ["04", "Damos seguimiento", "Mantenemos visibilidad hasta la entrega."],
      ],
      whyKicker: "Por qué Bajío Logistics",
      whyTitle: "Más que un proveedor Un equipo que se involucra",
      whyBody: "Nuestro objetivo es ayudarte a optimizar tus operaciones logísticas, reducir costos y hacer crecer tu negocio.",
      why: ["Atención personalizada", "Cobertura nacional", "Soluciones a la medida", "Enfoque en resultados", "Relaciones a largo plazo"],
      coverageKicker: "Alcance nacional",
      coverageTitle: "Tu operación, más lejos",
      coverageBody: "Con sede en San Juan del Río, Querétaro, coordinamos soluciones con alcance nacional y una red de proveedores que puede adaptarse a distintos corredores.",
      coverageLink: "Consulta disponibilidad para tu ruta",
      customersKicker: "Construimos relaciones",
      customersTitle: "El siguiente movimiento puede empezar aquí",
      customersBody: "Todavía no contamos con logotipos de clientes autorizados para publicar. La estructura queda lista para incorporarlos cuando estén disponibles.",
      customersLink: "Hablemos de tu operación",
      finalTitle: "Tu operación más eficiente. Nuestro compromiso",
      finalBody: "Cuéntanos qué necesitas mover y encontraremos el siguiente paso.",
      finalPrimary: "Solicitar cotización",
      finalSecondary: "Contactar al equipo",
    },
    services: {
      kicker: "Soluciones logísticas",
      title: "Lo que tu operación necesita para moverse mejor",
      body: "Un portafolio flexible para coordinar transporte, planeación y seguimiento con una mirada de negocio.",
      list: [
        { slug: "transporte", icon: "truck", title: "Transporte de mercancías", short: "Movimiento de mercancías con unidades alineadas a cada necesidad.", body: "Coordinamos el movimiento de mercancías con una lectura clara de origen, destino, tiempos y requerimientos de la operación." },
        { slug: "planeacion-logistica", icon: "route", title: "Planeación logística", short: "Análisis de rutas, frecuencias y capacidades para operar mejor.", body: "Convertimos necesidades de transporte en una planeación accionable: rutas, paradas, tiempos y comunicación." },
        { slug: "gestion-seguimiento", icon: "radar", title: "Gestión y seguimiento", short: "Control y visibilidad de tus operaciones.", body: "Acompañamos la operación para mantener información oportuna y dar seguimiento a los puntos importantes del movimiento." },
        { slug: "optimizacion-costos", icon: "gauge", title: "Optimización de costos", short: "Una mejor relación entre costo, servicio y confiabilidad.", body: "Revisamos la operación con enfoque en eficiencia, para identificar decisiones que ayuden a reducir fricciones y costos." },
        { slug: "red-proveedores", icon: "network", title: "Red de proveedores", short: "Acceso a una red para diferentes tipos de unidades y cobertura.", body: "Conectamos necesidades de operación con una red de proveedores de transporte, cuidando la coordinación y el seguimiento." },
        { slug: "consultoria-logistica", icon: "compass", title: "Consultoría logística", short: "Asesoría para mejorar la organización y el control de tu logística.", body: "Ponemos experiencia y estructura al servicio de decisiones logísticas más ordenadas, medibles y rentables." },
        { slug: "soluciones-personalizadas", icon: "target", title: "Soluciones personalizadas", short: "Una respuesta ajustada a la realidad de cada empresa.", body: "No buscamos encajar tu operación en una fórmula. Diseñamos una propuesta alrededor de tus necesidades y prioridades." },
      ],
      detailLabels: { benefits: "Lo que resuelve", process: "Cómo lo abordamos", cta: "Hablemos de tu operación" },
    },
    about: {
      kicker: "Cómo generamos valor",
      title: "Estrategia logística con objetivos claros",
      body: "",
      sections: [
        ["Misión", "Impulsar a las empresas con soluciones logísticas eficientes que generen resultados, contribuyendo al crecimiento y éxito en una cadena de valor sin interrupciones."],
        ["Visión", "Consolidarnos como un socio estratégico en logística, reconocidos por ofrecer operaciones confiables, medibles y sostenibles en el número de sectores que servimos."],
        ["Nuestra forma de trabajar", "Analizamos, anticipamos y formulamos necesidades para ofrecer soluciones a través de una visión conjunta, con equipos, procesos y mejora continua."],
      ],
      cta: "Conocer cómo trabajamos",
      adapted: "Soluciones que se adaptan a tu operación",
      timelineTitle: "Una historia que sigue en movimiento",
      timelineBody: "Los materiales disponibles todavía no contienen fechas históricas verificables.",
      timeline: [["01", "Fundación", "Primeras operaciones"], ["02", "Crecimiento", "Nuevas necesidades, nuevas rutas"], ["03", "Actualidad", "Coordinación con cobertura nacional"]],
      valuesTitle: "Lo que guía cada movimiento",
      values: [["Personalización", "Escuchamos antes de proponer."], ["Claridad", "Comunicamos lo importante."], ["Compromiso", "Damos seguimiento hasta el cierre."], ["Eficiencia", "Buscamos que cada decisión sume."]],
      headquarters: "Nuestra sede",
      headquartersBody: "San Juan del Río, Querétaro, México.",
    },
    coverage: {
      kicker: "Cobertura nacional",
      title: "Una sede en el Bajío. Un alcance que cruza el país",
      body: "Coordinamos soluciones de transporte con cobertura nacional. La disponibilidad final depende de la ruta, fecha y requerimientos de cada operación.",
      mapLabel: "Mapa de cobertura nacional",
      mapNote: "Representación visual. La disponibilidad se confirma por ruta.",
      cards: [["Sede", "San Juan del Río, Querétaro"], ["Alcance", "Cobertura a nivel nacional"], ["Coordinación", "Rutas, proveedores y seguimiento"]],
      cta: "Consulta disponibilidad para tu ruta",
    },
    customers: {
      kicker: "Clientes y relaciones",
      title: "La logística funciona mejor cuando se construye en equipo",
      body: "Trabajamos para convertir necesidades de transporte en soluciones claras y acompañadas.",
      logoTitle: "Algunos de nuestros clientes",
      logoBody: "Los materiales proporcionados no incluyen logotipos de clientes para publicación. Este espacio está preparado para agregarlos con autorización.",
      sectorsTitle: "Sectores que atendemos",
      sectorsBody: "La información sectorial específica aún no está documentada en los materiales disponibles. Podemos incorporarla aquí cuando se confirme.",
      caseTitle: "Casos de éxito",
      caseBody: "La estructura está lista para documentar el reto, la solución, la operación y los resultados de cada historia.",
      caseLabels: ["El reto", "La solución", "La operación", "Resultados"],
    },
    carriers: {
      kicker: "Para proveedores y transportistas",
      title: "Forma parte de nuestra red",
      body: "Conecta tu capacidad operativa con oportunidades de transporte y construye relaciones de largo plazo con Bajío Logistics.",
      primary: "Quiero ser proveedor",
      secondary: "Ya soy proveedor",
      benefitTitle: "Una relación clara desde el inicio",
      benefits: [["Coordinación", "Información clara para cada servicio."], ["Continuidad", "Una relación pensada para largo plazo."], ["Cobertura", "Participación en operaciones de distintas regiones."], ["Orden", "Proceso de alta con pasos visibles."]],
      lookingTitle: "Qué buscamos",
      lookingBody: "Propietarios de unidades, transportistas y empresas transportistas con disposición para colaborar con orden, comunicación y enfoque en el servicio.",
      equipmentTitle: "Tipos de unidades",
      equipmentBody: "La disponibilidad se revisa según la operación. El registro permite documentar las unidades y capacidades con las que cuentas.",
      equipment: ["Pickup", "1 tonelada", "3.5 toneladas", "Rabón", "Torton", "Tractocamión", "Caja seca", "Plataforma", "Refrigerado", "Otro"],
      processTitle: "Proceso de alta",
      process: [["01", "Registro", "Comparte tus datos básicos."], ["02", "Documentación", "Integra la información necesaria."], ["03", "Validación", "Revisamos los datos proporcionados."], ["04", "Alta", "Confirmamos la incorporación."], ["05", "Operaciones", "Comenzamos a coordinar servicios."]],
      requirementsTitle: "Requisitos",
      requirementsBody: "Los requisitos documentales específicos se definirán con el equipo de Bajío Logistics. El formulario está preparado para ampliar esta sección sin rehacer la experiencia.",
    },
    quote: {
      kicker: "Cotización",
      title: "Cuéntanos qué necesitas mover",
      body: "Completa los datos principales de tu operación. Al finalizar se abrirá WhatsApp con la cotización lista para revisar y enviar.",
      steps: ["Ruta", "Mercancía", "Unidad", "Fecha", "Contacto", "Comentarios"],
      fields: { origin: "Origen", destination: "Destino", postal: "Código postal", stops: "Número de paradas", goods: "Tipo de mercancía", weight: "Peso", dimensions: "Dimensiones", pallets: "Número de pallets", notes: "Información adicional", unit: "Unidad requerida", pickupDate: "Fecha de recolección", pickupTime: "Hora", deliveryDate: "Fecha deseada de entrega", company: "Empresa", name: "Nombre", role: "Puesto", phone: "Teléfono", whatsapp: "WhatsApp", email: "Correo electrónico", comments: "Requerimientos adicionales", privacy: "Acepto el aviso de privacidad.", next: "Continuar", back: "Regresar", submit: "Solicitar cotización", success: "Recibimos tu solicitud.", successBody: "Tu información quedó lista para ser atendida por el equipo de Bajío Logistics.", startOver: "Enviar otra solicitud" },
      units: ["No sé qué unidad necesito", "Pickup", "1 tonelada", "3.5 toneladas", "Rabón", "Torton", "Tractocamión", "Caja seca", "Plataforma", "Refrigerado", "Otro"],
    },
    contact: {
      kicker: "Contacto",
      title: "Hablemos de tu siguiente movimiento",
      body: "Selecciona el motivo de tu mensaje y cuéntanos cómo podemos ayudarte.",
      reasons: ["Solicitar cotización", "Información comercial", "Soy cliente", "Soy proveedor", "Quiero ser proveedor", "Operaciones", "Administración / Facturación", "Otro"],
      fields: { name: "Nombre", company: "Empresa", email: "Correo", phone: "Teléfono", subject: "Asunto", message: "Mensaje", submit: "Enviar mensaje", success: "Mensaje preparado", successBody: "Gracias. El formulario está listo para conectarse con el canal de atención de Bajío Logistics." },
      availabilityTitle: "Datos de contacto",
      availabilityBody: "Completa el formulario y se abrirá WhatsApp con tu mensaje listo para revisar y enviar al equipo de Bajío Logistics.",
    },
    register: {
      kicker: "Registro de proveedor",
      title: "Comencemos por conocerte",
      body: "Comparte la información básica de tu empresa y capacidad operativa. Al finalizar se abrirá WhatsApp con tu registro completo para revisarlo y enviarlo.",
      sections: ["Datos de empresa", "Datos de contacto", "Información fiscal", "Cobertura", "Flota y unidades", "Operadores", "Documentación", "Experiencia", "Comentarios"],
      fields: { company: "Empresa", legalName: "Razón social", name: "Nombre de contacto", email: "Correo", phone: "Teléfono", taxId: "RFC", coverage: "Estados o regiones de cobertura", fleet: "Descripción de flota", drivers: "Número de operadores", documents: "Documentación disponible", experience: "Experiencia relevante", comments: "Comentarios adicionales", privacy: "Acepto el aviso de privacidad.", submit: "Enviar registro por WhatsApp", success: "Registro listo para WhatsApp", successBody: "Se abrió WhatsApp con tu información cargada. Revisa el mensaje y presiona Enviar." },
    },
    faq: {
      kicker: "Preguntas frecuentes",
      title: "Respuestas para dar el siguiente paso",
      customerTitle: "Clientes",
      carrierTitle: "Proveedores",
      customer: [["¿Qué tipo de soluciones ofrecen?", "Coordinamos transporte de mercancías, planeación logística, gestión y seguimiento, optimización de costos, red de proveedores, consultoría y soluciones personalizadas."], ["¿Tienen cobertura nacional?", "Los materiales de Bajío Logistics indican cobertura a nivel nacional. La disponibilidad se confirma de acuerdo con la ruta, fecha y requerimientos de cada operación."], ["¿Cómo solicito una cotización?", "Puedes iniciar en la página de cotización y compartir los datos principales de tu operación para preparar una propuesta."], ["¿Puedo consultar el avance de un envío?", "La gestión y seguimiento forman parte del portafolio de servicios. Los mecanismos específicos se definirán con cada operación."]],
      carrier: [["¿Quién puede registrarse?", "Propietarios de unidades, transportistas y empresas transportistas interesados en colaborar con Bajío Logistics."], ["¿Qué unidades puedo registrar?", "El formulario contempla distintos tipos de unidades y una opción abierta para documentar capacidades adicionales."], ["¿Cuáles son los requisitos?", "Los requisitos documentales específicos aún no están publicados en los materiales disponibles. La estructura permite incorporarlos cuando se definan oficialmente."], ["¿Cómo es el proceso?", "Registro, documentación, validación, alta y operaciones."]],
    },
    footer: { columns: [["Empresa", ["Nosotros", "Historia", "Cobertura", "Clientes"]], ["Servicios", ["Transporte", "Planeación", "Seguimiento", "Optimización", "Consultoría"]], ["Clientes", ["Cotización", "Contacto", "Portal de clientes"]], ["Proveedores", ["Trabaja con nosotros", "Requisitos", "Registro", "Portal de proveedores"]]], legal: ["Aviso de privacidad", "Términos", "Cookies"], contact: "Contacto", placeholder: "Información disponible próximamente" },
  },
  en: {
    languageName: "English",
    localeLabel: "EN",
    nav: [["Home", "/en"], ["About Us", "/en/about"], ["Services", "/en/services"], ["Coverage", "/en/coverage"], ["Customers", "/en/customers"], ["Carriers", "/en/carriers"], ["Contact", "/en/contact"]],
    profile: { customer: "Customer", carrier: "Carrier", visitor: "Visitor" },
    headerCta: { customer: "Request a quote", carrier: "Become a carrier" },
    hero: {
      customer: { eyebrow: "LOGISTICS SOLUTIONS WITH NATIONWIDE COVERAGE", title: "More than transportation,", accent: "solutions that move your business forward", body: "We coordinate transportation, storage and integrated logistics so your supply chain can go further.", primary: "Request a quote", secondary: "Explore our services" },
      carrier: { eyebrow: "CARRIER NETWORK · OPERATIONS ACROSS MEXICO", title: "Let's grow together", accent: "Join our network", body: "Connect your operating capacity with transportation opportunities across different regions of Mexico.", primary: "Become a carrier", secondary: "I'm already a carrier" },
      visitor: { eyebrow: "BAJÍO LOGISTICS · YOUR CARGO IN MOTION", title: "Logistics that understands", accent: "what your operation needs", body: "Discover a clearer way to move cargo, coordinate carriers and make better decisions.", primary: "Learn about Bajío Logistics", secondary: "View services" },
    },
    home: {
      introKicker: "An ally for your operation", introTitle: "Logistics can also be a competitive advantage", introBody: "Bajío Logistics is a Mexican company specializing in logistics solutions and transportation, headquartered in San Juan del Río, Querétaro, with nationwide coverage.", introLink: "See how we work", capabilitiesTitle: "What can we do for your business?", capabilitiesBody: "We support every movement with coordination, visibility and a reliable carrier network.", capabilities: [{ icon: "truck", title: "Freight transportation", body: "Equipment aligned to each operation's needs." }, { icon: "route", title: "Logistics planning", body: "Efficient routes and lower operating cost." }, { icon: "radar", title: "Operations management", body: "Control and visibility for your shipments." }, { icon: "gauge", title: "Cost optimization", body: "More efficiency and profitability for your business." }], servicesKicker: "Capabilities that connect", servicesTitle: "Services to move forward with direction", servicesBody: "From a single move to an operation that needs structure, Bajío Logistics adapts coordination to your priorities.", servicesLink: "View all services", processKicker: "How we work", processTitle: "A coordinated operation from start to finish", process: [["01", "Understand", "We learn your operation, route and needs."], ["02", "Plan", "We define a clear solution for the move."], ["03", "Coordinate", "We align carriers, timing and communication."], ["04", "Follow through", "We keep visibility through delivery."]], whyKicker: "Why Bajío Logistics", whyTitle: "More than a provider. A team that gets involved", whyBody: "Our goal is to help you optimize logistics operations, reduce costs and grow your business.", why: ["Personalized attention", "Nationwide coverage", "Tailored solutions", "Results-focused", "Long-term relationships"], coverageKicker: "Nationwide reach", coverageTitle: "Take your operation further", coverageBody: "From our headquarters in San Juan del Río, Querétaro, we coordinate nationwide solutions through a carrier network that can adapt to different corridors.", coverageLink: "Check availability for your route", customersKicker: "We build relationships", customersTitle: "The next move can start here", customersBody: "The supplied materials do not include customer logos authorized for publication. The structure is ready to add them when available.", customersLink: "Let's talk about your operation", finalTitle: "Your operation, more efficient Our commitment", finalBody: "Tell us what you need to move and we'll find the next step.", finalPrimary: "Request a quote", finalSecondary: "Contact the team",
    },
    services: {
      kicker: "Logistics solutions", title: "What your operation needs to move better", body: "A flexible portfolio to coordinate transportation, planning and visibility with a business mindset.", list: [{ slug: "freight-transportation", icon: "truck", title: "Freight transportation", short: "Freight movement aligned to each need.", body: "We coordinate freight movement with a clear view of origin, destination, timing and operating requirements." }, { slug: "logistics-planning", icon: "route", title: "Logistics planning", short: "Route, frequency and capacity analysis for better operations.", body: "We turn transportation needs into actionable planning: routes, stops, timing and communication." }, { slug: "operations-management", icon: "radar", title: "Operations management & tracking", short: "Control and visibility for your operations.", body: "We support the operation with timely information and follow-up on the important points of each move." }, { slug: "cost-optimization", icon: "gauge", title: "Cost optimization", short: "A better balance of cost, service and reliability.", body: "We review the operation through an efficiency lens to identify decisions that reduce friction and cost." }, { slug: "carrier-network", icon: "network", title: "Carrier network", short: "A network for different equipment types and coverage.", body: "We connect operating needs with a transportation carrier network while caring for coordination and follow-up." }, { slug: "logistics-consulting", icon: "compass", title: "Logistics consulting", short: "Guidance to improve logistics organization and control.", body: "We bring experience and structure to more organized, measurable and profitable logistics decisions." }, { slug: "tailored-solutions", icon: "target", title: "Tailored logistics solutions", short: "A response shaped around each company's reality.", body: "We do not force your operation into a formula. We shape a proposal around your needs and priorities." }], detailLabels: { benefits: "What it solves", process: "How we approach it", cta: "Let's talk about your operation" },
    },
    about: { kicker: "How we create value", title: "Logistics strategy with clear objectives", body: "", sections: [["Mission", "Empower companies with efficient logistics solutions that generate results, contributing to growth and success in an uninterrupted value chain."], ["Vision", "Establish ourselves as a strategic logistics partner, recognized for reliable, measurable and sustainable operations across the sectors we serve."], ["Our way of working", "We analyze, anticipate and shape needs to offer solutions through a shared vision, with the right teams, processes and continuous improvement."]], cta: "Learn how we work", adapted: "Solutions adapted to your operation", timelineTitle: "A story still in motion", timelineBody: "The available materials do not include verifiable historical dates yet.", timeline: [["01", "Foundation", "First operations"], ["02", "Growth", "New needs, new routes"], ["03", "Today", "Coordination with nationwide coverage"]], valuesTitle: "What guides every move", values: [["Personal", "We listen before proposing."], ["Clarity", "We communicate what matters."], ["Commitment", "We follow through to close."], ["Efficiency", "We make every decision count."]], headquarters: "Our headquarters", headquartersBody: "San Juan del Río, Querétaro, Mexico." },
    coverage: { kicker: "Nationwide coverage", title: "A headquarters in the Bajío. Reach across Mexico", body: "We coordinate transportation solutions with nationwide coverage. Final availability depends on each route, date and operating requirement.", mapLabel: "Nationwide coverage map", mapNote: "Visual representation. Availability is confirmed by route.", cards: [["Headquarters", "San Juan del Río, Querétaro"], ["Reach", "Nationwide coverage"], ["Coordination", "Routes, carriers and visibility"]], cta: "Check availability for your route" },
    customers: { kicker: "Customers and relationships", title: "Logistics works better when it is built together", body: "We turn transportation needs into clear, supported solutions.", logoTitle: "Some of our customers", logoBody: "The supplied materials do not include customer logos authorized for publication. This space is ready to add them with approval.", sectorsTitle: "Industries we serve", sectorsBody: "Specific industry information has not yet been documented in the available materials. We can add it here once confirmed.", caseTitle: "Success stories", caseBody: "The structure is ready to document the challenge, solution, operation and results of each story.", caseLabels: ["The challenge", "Our solution", "The operation", "Results"] },
    carriers: { kicker: "For carriers and transportation providers", title: "Join our network", body: "Connect your operating capacity with transportation opportunities and build long-term relationships with Bajío Logistics.", primary: "Become a carrier", secondary: "I'm already a carrier", benefitTitle: "A clear relationship from day one", benefits: [["Coordination", "Clear information for every service."], ["Continuity", "A relationship built for the long term."], ["Coverage", "Participation across different regions."], ["Order", "A carrier onboarding process with visible steps."]], lookingTitle: "What we look for", lookingBody: "Owners of equipment, carriers and transportation companies ready to collaborate with order, communication and service focus.", equipmentTitle: "Equipment types", equipmentBody: "Availability is reviewed by operation. The registration form lets you document your equipment and capabilities.", equipment: ["Pickup", "1 ton", "3.5 ton", "Rabón", "Torton", "Tractor-trailer", "Dry van", "Flatbed", "Refrigerated", "Other"], processTitle: "Onboarding process", process: [["01", "Registration", "Share your basic information."], ["02", "Documentation", "Provide the required information."], ["03", "Validation", "We review the details provided."], ["04", "Approval", "We confirm your onboarding."], ["05", "Operations", "We begin coordinating services."]], requirementsTitle: "Requirements", requirementsBody: "Specific document requirements will be defined with the Bajío Logistics team. The form is ready to expand this section without rebuilding the experience." },
    quote: { kicker: "Request a quote", title: "Tell us what you need to move", body: "Share the main details of your operation. When you finish, WhatsApp will open with the quote ready to review and send.", steps: ["Route", "Cargo", "Equipment", "Date", "Contact", "Comments"], fields: { origin: "Origin", destination: "Destination", postal: "Postal code", stops: "Number of stops", goods: "Cargo type", weight: "Weight", dimensions: "Dimensions", pallets: "Number of pallets", notes: "Additional information", unit: "Equipment needed", pickupDate: "Pickup date", pickupTime: "Time", deliveryDate: "Desired delivery date", company: "Company", name: "Name", role: "Role", phone: "Phone", whatsapp: "WhatsApp", email: "Email", comments: "Additional requirements", privacy: "I accept the privacy notice.", next: "Continue", back: "Back", submit: "Request a quote", success: "Your request is ready.", successBody: "Your information is ready for the Bajío Logistics team to follow up.", startOver: "Start another request" }, units: ["I don't know what equipment I need", "Pickup", "1 ton", "3.5 ton", "Rabón", "Torton", "Tractor-trailer", "Dry van", "Flatbed", "Refrigerated", "Other"] },
    contact: { kicker: "Contact", title: "Let's talk about your next move", body: "Choose a reason for your message and tell us how we can help.", reasons: ["Request a quote", "Sales inquiry", "Current customer", "Current carrier", "Become a carrier", "Operations", "Billing / Administration", "Other"], fields: { name: "Name", company: "Company", email: "Email", phone: "Phone", subject: "Subject", message: "Message", submit: "Send message", success: "Message ready", successBody: "WhatsApp opened with your information loaded. Review the message and press Send." }, availabilityTitle: "Contact details", availabilityBody: "Complete the form and WhatsApp will open with your message ready to review and send to the Bajío Logistics team." },
    register: { kicker: "Carrier registration", title: "Let's start by getting to know you", body: "Share your company's basic information and operating capacity. When you finish, WhatsApp will open with your complete registration ready to review and send.", sections: ["Company information", "Contact information", "Tax information", "Coverage", "Fleet and equipment", "Drivers", "Documents", "Experience", "Additional information"], fields: { company: "Company", legalName: "Legal name", name: "Contact name", email: "Email", phone: "Phone", taxId: "Tax ID", coverage: "States or regions covered", fleet: "Fleet description", drivers: "Number of drivers", documents: "Available documentation", experience: "Relevant experience", comments: "Additional comments", privacy: "I accept the privacy notice.", submit: "Send registration on WhatsApp", success: "Registration ready for WhatsApp", successBody: "WhatsApp opened with your information loaded. Review the message and press Send." } },
    faq: { kicker: "Frequently asked questions", title: "Answers for the next step", customerTitle: "Customers", carrierTitle: "Carriers", customer: [["What solutions do you offer?", "We coordinate freight transportation, logistics planning, operations management and tracking, cost optimization, carrier network, consulting and tailored solutions."], ["Do you have nationwide coverage?", "Bajío Logistics' materials indicate nationwide coverage. Availability is confirmed by route, date and each operation's requirements."], ["How do I request a quote?", "Start on the quote page and share the main details of your operation to prepare a proposal."], ["Can I track a shipment?", "Operations management and tracking are part of the service portfolio. Specific mechanisms are defined for each operation."]], carrier: [["Who can register?", "Equipment owners, carriers and transportation companies interested in working with Bajío Logistics."], ["What equipment can I register?", "The form supports several equipment types and an open option for additional capabilities."], ["What are the requirements?", "Specific document requirements are not yet published in the available materials. The structure can be updated when officially defined."], ["What is the process?", "Registration, documentation, validation, approval and operations."]] },
    footer: { columns: [["Company", ["About Us", "Our Story", "Coverage", "Customers"]], ["Services", ["Transportation", "Planning", "Tracking", "Optimization", "Consulting"]], ["Customers", ["Request a quote", "Contact", "Customer portal"]], ["Carriers", ["Work with us", "Requirements", "Registration", "Carrier portal"]]], legal: ["Privacy notice", "Terms", "Cookies"], contact: "Contact", placeholder: "Information available soon" },
  },
};

export const serviceSlugMap = {
  es: { transporte: "transporte", "planeacion-logistica": "planeacion-logistica", "gestion-seguimiento": "gestion-seguimiento", "optimizacion-costos": "optimizacion-costos", "red-proveedores": "red-proveedores", "consultoria-logistica": "consultoria-logistica", "soluciones-personalizadas": "soluciones-personalizadas" },
  en: { "freight-transportation": "freight-transportation", "logistics-planning": "logistics-planning", "operations-management": "operations-management", "cost-optimization": "cost-optimization", "carrier-network": "carrier-network", "logistics-consulting": "logistics-consulting", "tailored-solutions": "tailored-solutions" },
};
